### ISSUE TITLE
MapKit не собирается под Xcode 13.3.1

### ISSUE THREAD

**Issue by osolodkin** [yandex/mapkit-ios-demo#141]
при сборке под Xcode 13.3.1 выдает ошибку
`in /Users/user/Documents/XcodeProjects/project/Pods/YandexMapKit/YandexMapKit.framework/YandexMapKit(YMKLinearRing_Binding.o), section _DATA/_bss has type zero-fill but non-zero file offset file '/Users/user/Documents/XcodeProjects/project/Pods/YandexMapKit/YandexMapKit.framework/YandexMapKit' for architecture arm64`

если откатиться на Xcode 13.2.1, то сборка проходит успешно без каких-либо изменений в коде
https://developer.apple.com/download/all/?q=xcode%2013.2.1

**Comment by alexeybolv** [comment]
Такая же проблема.

**Comment by bobermiha** [comment]
+

**Comment by aleks990822** [comment]
я даже не могу обновить приложение, что бы поменять токен яндекс доставки, из-за яндекса, трэш

**Comment by akbarpulatov** [comment]
Есть новости?

**Comment by Kodryan** [comment]
на м1 собирается если запустить Xcode под розетой

**Comment by Roman-Kerimov** [comment]
> Есть новости?

Всего каких‐то две недели прошло с момента регистрации issue. Надо проявить терпение и команде Яндекса хотя‐бы 2 года

**Comment by Roman-Kerimov** [comment]
> на м1 собирается если запустить Xcode под розетой

Только под симулятор, но не под устройство

**Comment by bobermiha** [comment]
Здравствуйте, Михаил

Мы уже в курсе данной ситуации с Xcode 13.3. Наши специалисты занимаются решением, и рассчитывают исправить ситуацию в ближайшем обновлении MapKit. Точных сроков пока вам назвать не смогу, но мы регулярно напоминаем о вопросе разработчикам.
Надеемся на ваши терпение и понимание, и приносим извинения за доставленные неудобства.

Неделю назад писал им.

**Comment by Roman-Kerimov** [comment]
> Неделю назад писал им.

Ответили что‐нибудь спустя неделю?

**Comment by bobermiha** [comment]
> Ответили что‐нибудь спустя две недели уже?

Да ответили: "К сожалению, пока хорошими новостями поделиться не можем, команда ещё разбирается в этой ситуации."

Приходится через костыль решать данную проблему. Из нового Xcode вытаскиваю DeviceSupport папку с 15.4 и собираю проект в 13.2.1.

**Comment by c-villain** [comment]
кому надо, вот [версия](https://github.com/c-villain/YandexMapsMobile), работающая на Xcode > 13.3 в режиме Розетты, собирается как на девайс, так и на симулятор...

**Comment by bobermiha** [comment]
> кому надо, вот [версия](https://github.com/c-villain/YandexMapsMobile), работающая на Xcode > 13.3 в режиме Розетты, собирается как на девайс, так и на симулятор...
Это настолько странно... Я не могу собрать на интеле, зато на розетте все работает)

**Comment by debug45** [comment]
Уже и Xcode 13.4 сегодня вышел, а воз и ныне там...

**Comment by Roman-Kerimov** [comment]
> Уже и Xcode 13.4 сегодня вышел, а воз и ныне там...

Ну к выходу Xcode 14 может и добавят поддержку 13.3

**Comment by kaannesinn** [comment]
Thanks for 4.1.0 👍 but after installing new version, we see that some classes and variables don't exist in the sdk.
- YMKColoredPolylineMapObject -> doesn't exist
- YMKPolylineMapObject doesn't have strokeColor
- YMKDrivingAnnotationLanguage -> doesn't exist
- etc

Will these previous classes be added with later versions or are there any changes other than the Xcode13.3.x fix on the 4.1.0-full version?

Because of these changes we like we aren't able to update our application on AppStore.

4.1.0-full version is like 4.1.0-lite version, is there any misunderstanding on our side or could we use another classes/variables instead of these new changes above?

**Comment by imseleznev-yandex** [comment]
There are some slight changes in API, but functionality was not reduces. English documentation is on the way (couple of days). 

Instead of YMKColoredPolylineMapObject now you should use YMKColoredPolylineMapObject 
YMKColoredPolylineMapObject has [setStrokeColorWithColor](https://yandex.ru/dev/maps/mapkit/doc/ios-ref/full/Classes/YMKPolylineMapObject.html#-setStrokeColorWithColor`)
Instead of YMKDrivingAnnotationLanguage you can now use [AnnotationLanguage](https://yandex.ru/dev/maps/mapkit/doc/ios-ref/full/Enums/YMKAnnotationLanguage.html)

**Comment by kaannesinn** [comment]
Hmm ok, waiting for the documentation for other changes 👍 

As you said I have done it successfully:
+ Instead of YMKColoredPolylineMapObject now you should use YMKPolylineMapObject
+ YMKPolylineMapObject has setStrokeColorWithColor
+ Instead of YMKDrivingAnnotationLanguage you can now use AnnotationLanguage
+ updatePolyline has updateGeometry bool -> is given as true
+ addColoredPolyline is now addPolyline

? setLocationManagerWith is removed -> there is no other thing instead of it (I can't see)

**After these changes I have to add these to AppDelegate for showing map layers clearly:**
     ```
   let locale = (Locale.preferredLanguages.first ?? "tr-TR").replacingOccurrences(of: "-", with: "_")
        YMKMapKit.setLocale(locale)
        
        YMKMapKit.sharedInstance()
```

**Comment by MegakoMar** [comment]
> Добрый день! Мы обновили мапкит до 4.1.0, где эта проблема исправлена. Документация в процессе обновления.
Добрый день, добавил в проект YandexMapsMobile 4.1.0, но теперь крашится проект со следующей ошибкой "Thread 1: "+[YMKMapKit setApiKey:]: unrecognized selector sent to class 0x103850698"  ". В #130 задан такой же вопрос, но там нет ответа. Пробовал как lite, так и full версию

**Comment by traktor74** [comment]
> Добрый день! Мы обновили мапкит до 4.1.0, где эта проблема исправлена. Документация в процессе обновления.

а поддержки SPM в 4.1.0 все также нет?

**Comment by c-villain** [comment]
> > Добрый день! Мы обновили мапкит до 4.1.0, где эта проблема исправлена. Документация в процессе обновления.
> 
> а поддержки SPM в 4.1.0 все также нет?

@traktor74  Можешь [отсюда]( https://github.com/c-villain/YandexMapsMobile) взять

**Comment by DanKamilov** [comment]
Есть решение? в Xcode 14.3 запрет на розетту. До сих пор команда ничего не смогла сделать? 4000 разработчиков Яндекса бессильны)?
