### ISSUE TITLE
YMKSearchRelatedPlacesObjectMetadata problem

### ISSUE THREAD

**Issue by goodprt** [yandex/mapkit-ios-demo#87]
func onSearchSuggestionResponse(_ response: YMKSearchResponse) {
        let metadata = response.metadata

        let mapObjects = mapView.mapWindow.map.mapObjects
        mapObjects.clear()
        if let mapBox = metadata.boundingBox {
            let position = mapView.mapWindow.map.cameraPosition(with: mapBox)
            mapView.mapWindow.map.move(with: position,
                                       animationType: YMKAnimation(type: YMKAnimationType.smooth, duration: 1),
                                       cameraCallback: nil)
        }
        
        if let searchItem = response.collection.children.first {
            if let relatedPlaces = searchItem.obj?.metadataContainer.getItemOf(YMKSearchRelatedPlacesObjectMetadata.self) as? YMKSearchRelatedPlacesObjectMetadata {

                **let companiesNearby = relatedPlaces.companiesNearby //always nil**
                //let similarPlaces = relatedPlaces.similarPlaces
                
                for company in companiesNearby {
                    if let category = company.category, categoriesWithImage[category] != nil
                    {
                        if let uri = company.uri {
                            if let point = company.point {
                                let placemark = mapObjects.addPlacemark(with: point)
                                placemark.userData = uri
                                placemark.addTapListener(with: self)
                                placemark.setIconWith(categoriesWithImage[category] ?? UIImage())
                            }
                        }
                    }
                }
            }
        }
        
    }

**Comment by goodprt** [comment]
I am trying to get a list of companies that are next to a search result.

**Comment by elricbk** [comment]
Thanks for the report.  This field was originally intended to be used for companies located near toponyms.  But now, as far as I can see, this functionality is disabled.  And the field must be removed from the API.

**Comment by elricbk** [comment]
I've closed the issue as we can do nothing about this field being always `nil` except for removing it completely.

**Comment by goodprt** [comment]
Thanks for your answer! Сan you advise me, how I can implement such functionality using available ways?

**Comment by elricbk** [comment]
There are a couple of options, both require an additional request:

* If you want to find any companies nearby, you can take a point from the the search result and use it for a reverse search request with the `.biz` type.
* Another option, if you want to search for companies that are somehow similar to the current one, you can:
  - take a company point (from `geometry`)
  - make a small search window from this point
  - take the category name from the company
  - make a regular text search with the category name, the search window, and the `.biz` search type
  - since a text search can increase / shift the search window, you may need to further filter the results by distance/search window

**Comment by goodprt** [comment]
Thanks for all!
